{% set name = "pyobjc-framework-CoreText" %}
{% set version = "10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyobjc-framework-CoreText-{{ version }}.tar.gz
  sha256: 2c157d82373b8128afb9a61df26cbf029896adf86bf86876ce3f8cc3c3f3cb1b

build:
  skip: true  # [not osx]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - pyobjc-core >={{ version }}
    - pyobjc-framework-cocoa >={{ version }}
    - pyobjc-framework-quartz >={{ version }}

test:
  imports:
    - PyObjCTools
    - CoreText
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the framework CoreText on macOS
  doc_url: https://pythonhosted.org/pyobjc-framework-CoreText/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
