{% set name = "pyobjc-framework-CoreText" %}
{% set version = "11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.replace('-', '_').lower() }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: a68437153e627847e3898754dd3f13ae0cb852246b016a91f9c9cbccb9f91a43

build:
  skip: true  # [not osx]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - pyobjc-core >={{ version }}
    - pyobjc-framework-cocoa >={{ version }}
    - pyobjc-framework-quartz >={{ version }}

test:
  imports:
    - PyObjCTools
    - CoreText
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the framework CoreText on macOS
  doc_url: https://pythonhosted.org/pyobjc-framework-CoreText/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - rxm7706
